spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
  security:
    jwt:
      secret: ${JWT_SECRET}
      access-expiration: ${ACCESS_EXPIRATION}
      refresh-expiration: ${REFRESH_EXPIRATION}